"""add ojt_adviser and program to student profiles

Revision ID: 143ae4d78ade
Revises: 94086360ff18
Create Date: 2026-02-08 17:38:32.860954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143ae4d78ade'
down_revision = '94086360ff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ojt_adviser', sa.String(length=150), nullable=True))
        batch_op.alter_column('program',
               existing_type=postgresql.ENUM('DLMOT', 'DEET', 'DMET', 'DCvET', 'DCpET', 'DRET', 'DECET', name='student_program_enum'),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('program',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('DLMOT', 'DEET', 'DMET', 'DCvET', 'DCpET', 'DRET', 'DECET', name='student_program_enum'),
               existing_nullable=True)
        batch_op.drop_column('ojt_adviser')

    # ### end Alembic commands ###
