"""create moa_prospects table

Revision ID: 26cbf8bf022f
Revises: d4b14786f366
Create Date: 2026-02-08 15:25:49.364935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cbf8bf022f'
down_revision = 'd4b14786f366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moa_prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('contact_position', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('moa_file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('EMAILED_TO_HTE', 'FOR_SIGNATURE', 'ULCO', 'RETRIEVED_FROM_ULCO', 'APPROVED', 'CANCELLED', name='moa_prospect_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moa_prospects')
    # ### end Alembic commands ###
