"""add_logo_path_to_hte

Revision ID: 28f8e9b4aa87
Revises: 539da8dd868f
Create Date: 2026-03-03 06:22:18.421294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f8e9b4aa87'
down_revision = '539da8dd868f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
