"""store moa files in database

Revision ID: 32f5e64878af
Revises: 7f2c1b9a4d10
Create Date: 2026-04-23 08:14:35.331480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f5e64878af'
down_revision = '7f2c1b9a4d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoranda_of_agreement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('document_mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('document_blob', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('document_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoranda_of_agreement', schema=None) as batch_op:
        batch_op.drop_column('document_size')
        batch_op.drop_column('document_blob')
        batch_op.drop_column('document_mime_type')
        batch_op.drop_column('document_filename')

    # ### end Alembic commands ###
