"""update document items for nested documents feature

Revision ID: 4636095ec635
Revises: ca39c40a858b
Create Date: 2026-03-08 19:08:06.211591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4636095ec635'
down_revision = 'ca39c40a858b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_items_section'), ['section'], unique=False)
        batch_op.drop_constraint(batch_op.f('document_items_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_items', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_uploaded_documents_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_documents_section'), ['section'], unique=False)
        batch_op.create_foreign_key(None, 'uploaded_documents', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_uploaded_documents_section'))
        batch_op.drop_index(batch_op.f('ix_uploaded_documents_parent_id'))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('item_type')
        batch_op.drop_column('section')

    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('document_items_parent_id_fkey'), 'document_items', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_document_items_section'))
        batch_op.drop_index(batch_op.f('ix_document_items_parent_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
