"""add uploaded documents table

Revision ID: 539da8dd868f
Revises: 143ae4d78ade
Create Date: 2026-02-08 19:21:32.650489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539da8dd868f'
down_revision = '143ae4d78ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_documents')
    # ### end Alembic commands ###
