"""add hte reviews

Revision ID: 998b79dd06dd
Revises: badb7935ebdd
Create Date: 2026-03-06 08:09:25.139380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998b79dd06dd'
down_revision = 'badb7935ebdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hte_reviews', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hte_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
