"""add hte reviews

Revision ID: badb7935ebdd
Revises: 28f8e9b4aa87
Create Date: 2026-03-06 06:33:51.098884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badb7935ebdd'
down_revision = '28f8e9b4aa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hte_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hte_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='hte_review_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hte_id'], ['host_training_establishments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hte_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hte_reviews_hte_id'), ['hte_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hte_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hte_reviews_student_user_id'), ['student_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hte_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hte_reviews_student_user_id'))
        batch_op.drop_index(batch_op.f('ix_hte_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_hte_reviews_hte_id'))

    op.drop_table('hte_reviews')
    # ### end Alembic commands ###
