"""Add description and website to HTE

Revision ID: d4b14786f366
Revises: 4a1ba56ca97f
Create Date: 2026-02-04 07:42:47.552828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b14786f366'
down_revision = '4a1ba56ca97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
